WebApplication1/Controllers/CategoryController.cs
using System;
using System.Web.Mvc;
using Model.DAO;
using Model.EF;

namespace WebComic.Controllers
{
    public class CategoryController : Controller
    {
        // GET
        public ActionResult Index()
        {
            CategoryDAO categoryDao = new CategoryDAO();

            var list = categoryDao.List();
            ViewBag.ListCategory = list;
            return View();
        }

        [HttpPost]
        public ActionResult Delete()
        {
            category category = new category();
            category.CategoryId = Convert.ToInt32(Request["id"]);
            return Content("true");
        }


        public ActionResult _Navbar()
        {
            CategoryDAO categoryDao = new CategoryDAO();
            ViewBag.Data = categoryDao.List();

            return PartialView("_Navbar");
        }
    }
}

WebApplication1/Controllers/ChapterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebComic.Controllers
{
    public class ChapterController : Controller
    {
        // GET
        public ActionResult Index(int chapterId)
        {
            ChapterDAO chapterDao = new ChapterDAO();
            chapterDao.UpdateView(chapterId);

            if (Request.Cookies["history"] != null)
            {
                // var json = Request.Cookies["history"].Value;
                // JObject o = JObject.Parse(json);
                // JArray a = (JArray)o[0];
                // JToken[] list = a.ToArray();
            }
            else
            {
                SortedList<int, String> ints = new SortedList<int, String>();

                ints.Add(chapterId, String.Format("{0:dd/MM/yyyy hh:mm }", DateTime.Now));


                var cookie = new HttpCookie("history", JsonConvert.SerializeObject(ints));
                cookie.Expires = DateTime.Now.AddDays(30);
                Response.AppendCookie(cookie);
            }

            ViewBag.Data = chapterDao.Select(chapterId);

            // ViewBag.Title  =  

            return View();
        }
    }
}

WebApplication1/Controllers/ComicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.EF;
using Model.Models;

namespace WebComic.Controllers
{
    public class ComicController : Controller
    {
        // GET
        public ActionResult Index(int comicId)
        {
            ComicDAO comicDao = new ComicDAO();
            comic comic = comicDao.GetComicAs(comicId).Result;


            ViewBag.Title = comic.NameComic;
            ViewBag.Data = comic;

            return View();
        }

        public ActionResult Home()
        {
            var page = Convert.ToInt32(Request["page"]);

            if (page < 1)
            {
                page = 1;
            }

            ComicDAO comicDao = new ComicDAO();
            var list = comicDao.ListPage(new Pagination(12, page));

            // news comic

            List<comic> comics = list.Comics;
            ViewBag.ComicsMain = comics;

            int numPage = list.PageSize;
            ViewBag.Numpage = numPage;

            ViewBag.Page = page;

            return View();
        }

        public ActionResult ComicCategory()
        {
            return View();
        }

        public ActionResult _Slide()
        {
            ComicDAO comicDao = new ComicDAO();
            ViewBag.Data = comicDao.SlideComic();

            return PartialView("_Slide");
        }

        public ActionResult _ComicNew()
        {
            ComicDAO comicDao = new ComicDAO();
            ViewBag.Data = comicDao.NewComic().OrderBy(comic => comic.ReleaseDate);

            return PartialView("_ComicNew");
        }


        // [HttpPost]
        // public ActionResult SearchAdvanced()
        // {
        //     
        // }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.EF;
using Model.Models;
using Newtonsoft.Json;

namespace WebComic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ComicDAO comicDao = new ComicDAO();
            var list = comicDao.ListPage(new Pagination(12, 1));

            // news comic
            List<comic> comics = list.Comics;
            ViewBag.ComicsMain = comics;

            //phan trang
            int numPage = list.PageSize;
            ViewBag.Numpage = numPage;

            int page = list.Page;
            ViewBag.Page =page;
            
            return View();
        }
        

        [HttpPost]
        public ActionResult GetList()
        {
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            String searchValue = Request["search[value]"];
            String sortColumnName = Request["columns[" + Request["order[0][column]"] + "][data]"];
            String sortDirection = Request["order[0][dir]"];


            CategoryDAO categoryDao = new CategoryDAO();

            List<category> list = categoryDao.List();

            int totalRow = list.Count;

            //Tìm kiếm


            if (!String.IsNullOrEmpty(searchValue))
            {
                list = categoryDao.ListSearch(searchValue);
            }

            int filterRow = list.Count;

            //Sắp xếp


            // list = list.(order )

            //Phân trang

            list = list.Skip(start).Take(length).ToList();

            return Json(
                new {data = list, draw = Request["draw"], recordsTotal = totalRow, recordsFiltered = filterRow},
                JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication1/Views/Comic/Home.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Activities.Statements
@using Model.EF
@{
    Html.RenderAction("_Slide", "Comic");
}
@* main *@
<div class="main bg-main">

    <h2>Truyện mới cập nhật</h2>

    <div class="row">

        @foreach (comic comic in  ViewBag.ComicsMain)
        {
            <div class="col-lg-2 col-sm-3 col-6">

                <div class="comic-item">
                    <a href="@Url.Action("Index", "Comic", new {comicId = @comic.ComicId})">
                        <div class="item-main">
                            <div class="img-cover">
                                <div class="img-bg bg-img-full" url-bg="@comic.CommicBanner"></div>
                            </div>
                            @if (comic.chapters.Count > 0)
                            {
                                <div class="new-chapter">
                                    <a href="@Url.Action("Index", "Chapter", new {chapterId = comic.chapters.Max(chapter => chapter.ChapterId)})">@comic.chapters.Max(chapter => chapter.NameChapter)</a>
                                </div>

                                if (comic.chapters.ToList().Sum(chapter => chapter.View) / comic.chapters.Count > 2000)
                                {
                                    <div class="chpter-hot">
                                        Hot
                                    </div>
                                }
                            }
                        </div>
                    </a>

                    <div class="name-comic text-light">
                        <a href="@Url.Action("Index", "Comic", new {comicId = @comic.ComicId})">@comic.NameComic</a>
                    </div>
                </div>

            </div>
        }


    </div>

    @* paging *@

    <nav aria-label="Page navigation example" class="page">
        <ul class="pagination justify-content-end">

            @if (ViewBag.Page > 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="@Url.Action("Home", "Comic", new {page = ViewBag.Page - 1})" tabindex="-1" aria-disabled="true">
                        <i class="fas fa-chevron-left"></i>
                    </a>
                </li>
            }


            @for (var i = 1; i <= ViewBag.Numpage; i++)
            {
                if (ViewBag.Page == i)
                {
                    <li class="page-item active">
                        <a class="page-link active" href="@Url.Action("Home", "Comic", new {page = i})">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link active" href="@Url.Action("Home", "Comic", new {page = i})">@i</a>
                    </li>
                }
            }

            @if (ViewBag.Page < ViewBag.Numpage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Home", "Comic", new {page = ViewBag.Page + 1})">
                        <i class="fas fa-chevron-right"></i>
                    </a>
                </li>
            }

        </ul>
    </nav>

</div>

@{
    Html.RenderAction("_ComicNew", "Comic");
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Activities.Statements
@using Model.EF
@{
    Html.RenderAction("_Slide", "Comic");
}
@* main *@
<div class="main bg-main">

    <h2>Truyện mới cập nhật</h2>

    <div class="row">

        @foreach (comic comic in  ViewBag.ComicsMain)
        {
            <div class="col-lg-2 col-sm-3 col-6">

                <div class="comic-item" id-comic="@comic.ComicId">
                    <a href="@Url.Action("Index", "Comic", new {comicId = @comic.ComicId})">
                        <div class="item-main">
                            <div class="img-cover">
                                <div class="img-bg bg-img-full" url-bg="@comic.CommicBanner"></div>
                            </div>
                            @if (comic.chapters.Count > 0)
                            {
                                
                                <div class="new-chapter">
                                    <a href="@Url.Action("Index", "Chapter", new {chapterId = comic.chapters.Max(chapter => chapter.ChapterId)})">@comic.chapters.Max(chapter => chapter.NameChapter)</a>
                                </div>
                                
                                if (comic.chapters.ToList().Sum(chapter => chapter.View) / comic.chapters.Count > 2000)
                                {
                                    <div class="chpter-hot">
                                        Hot
                                    </div>
                                }
                                
                            }

                        </div>
                    </a>

                    <div class="name-comic text-light">
                        <a href="@Url.Action("Index", "Comic", new {comicId = @comic.ComicId})">@comic.NameComic</a>
                    </div>
                </div>

            </div>
        }


    </div>

    @* paging *@

    <nav aria-label="Page navigation example" class="page">
        <ul class="pagination justify-content-end">

            @if (ViewBag.Page > 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" href="@Url.Action("Home", "Comic", new {page = ViewBag.Page - 1})" tabindex="-1" aria-disabled="true">
                        <i class="fas fa-chevron-left"></i>
                    </a>
                </li>
            }


            @for (var i = 1; i <= ViewBag.Numpage; i++)
            {
                if (ViewBag.Page == i)
                {
                    <li class="page-item active">
                        <a class="page-link active" href="@Url.Action("Home", "Comic", new {page = i})">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link active" href="@Url.Action("Home", "Comic", new {page = i})">@i</a>
                    </li>
                }
            }

            @if (ViewBag.Page < ViewBag.Numpage)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action("Home", "Comic", new {page = ViewBag.Page + 1})">
                        <i class="fas fa-chevron-right"></i>
                    </a>
                </li>
            }

        </ul>
    </nav>

</div>

@{
    Html.RenderAction("_ComicNew", "Comic");
}

WebApplication1/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="~/Upload/Logo/logo.png">

    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sarabun">
    <link rel="stylesheet" href="~/Content/jquery-confirm.min.css">
    <link rel="stylesheet" href="~/Content/font.min.css">
    <link rel="stylesheet" href="~/Content/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Content/mystyle.css">

</head>
<body >
@{
    Html.RenderAction("_Navbar", "Category");
}

<div class="container">

    @RenderBody()

</div>


<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/boostrap.min.js"></script>
<script src="~/Scripts/popper.min.js"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<script src="~/Scripts/owl.carousel.min.js"></script>
<script src="~/Scripts/font.min.js"></script>
<script src="~/Scripts/slide.js"></script>
<script src="~/Scripts/load-bg.js"></script>

</body>
</html>

WebApplication1/Views/Shared/_Navbar.cshtml
@using Model.EF
<nav class="navbar navbar-expand-lg navbar-light  container-fluid bg-nav">
    <div class="container">
        <a class="navbar-brand" href="~/Home">
            <img src="~/Upload/Config/logo.png" height="50px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" id="show-category">Thể loại</a>
                    <div class="menu-category">
                        <div class="list-category">
                            <div class="row">

                                @foreach (category c in ViewBag.Data)
                                {
                                    <div class="col-md-2 col-6 item-category">
                                        <a href="">@c.NameCategory</a>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="@Url.Action("Index", "Category")">Lọc nâng cao</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="@Url.Action("Index", "Category")">Đăng nhập</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="@Url.Action("Index", "Category")">Đăng ký</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="">
                <input class="form-control ip-search" type="search" placeholder="Nhập tên chuyện ">
                <button class="btn btn-white my-2" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>
        </div>
    </div>
</nav>